### ISSUE TITLE
Uwagi

### ISSUE THREAD

**Issue by MarcinCiura** [Radioaktyv/JSProjekt#1]
1. Co to jest? Proszę dopisać `README.md`.
2. [Kolory smutne](https://github.com/Radioaktyv/JSProjekt/blob/3c1848846f44d4c864ae04a3fad6eba03a91f470/main.py#L17) (3. rozdział).
3. [Unikać backslashów](https://github.com/Radioaktyv/JSProjekt/blob/3c1848846f44d4c864ae04a3fad6eba03a91f470/main.py#L35) (2. rozdział). Np. [tu](https://github.com/Radioaktyv/JSProjekt/blob/3c1848846f44d4c864ae04a3fad6eba03a91f470/main.py#L89) otoczyć cały warunek nawiasami.
4. [`flag = False`](https://github.com/Radioaktyv/JSProjekt/blob/3c1848846f44d4c864ae04a3fad6eba03a91f470/main.py#L120) itd. Na końcu `return Flag`.
5. Importy posortować (2. rozdział).
6. `TestColors` zbędne. Wyrzucić.
7. `self.assertEqual(array, test_array)`.
8. [`assertTrue()`](https://github.com/Radioaktyv/JSProjekt/blob/3c1848846f44d4c864ae04a3fad6eba03a91f470/test.py#L53), `assertFalse`.

Dobry początek, ale — jak rozumiem — to jakaś gra logiczna. Gdzie AI?

**Comment by Radioaktyv** [comment]
Szanowny Panie Doktorze,
Naniosłem poprawki podane przez Pana. W rozpisce tematów podanych na platformie ELF nie było nic o AI więc myślałem aby stworzyć grę na dwóch graczy.
Z wyrazami szacunku,
Łukasz Murdzia

**Comment by MarcinCiura** [comment]
Dziękuję za odpowiedź. Kolejne uwagi:
1. Kolory dalej smutne (3. rozdział).
2. z `-1`, `0` i `1` do `turn` i do zawartości `array` zrobić nazwane stałe (2. rozdział). Uprościć `next_turn()`: używać `return ...` wewnątrz bloków `if` i `else`.
3. [Zbędny warunek](https://github.com/Radioaktyv/JSProjekt/blob/1e8385c7c44027865532bdefce72807b0fc68df5/main.py#L77).
4. [Tu](https://github.com/Radioaktyv/JSProjekt/blob/1e8385c7c44027865532bdefce72807b0fc68df5/main.py#L91) użyć `if ... == ... == ... == ... == turn:`.

Abstrahując od tematu, pana program nie spełnia żadnych wymagań dotyczących projektów. Nie ma ani jednej klasy. Nie ma wyjątków. Nie ma *list comprehensions*. Proszę przesłać link do tego repozytorium drowi Gąciarzowi i zapytać się go, jako autora zadania, czy w zadaniu chodziło o *Connect 4* bez AI.

**Comment by Radioaktyv** [comment]
Szanowny Panie Doktorze,
W związku z Pana zaleceniami dokonałem niezbędnych poprawek w kodzie, dodałem również AI. 
Z wyrazami szacunku
Łukasz Murdzia

**Comment by MarcinCiura** [comment]
Dziękuję za zmiany.
1. [Importy posortować](https://github.com/Radioaktyv/JSProjekt/blob/4452d984a887c3c1959d48c2af6cf81f9fc182d7/main.py#L2) (2. rozdział). [Tu też](https://github.com/Radioaktyv/JSProjekt/blob/4452d984a887c3c1959d48c2af6cf81f9fc182d7/test.py#L1).
2. [To też](https://github.com/Radioaktyv/JSProjekt/blob/4452d984a887c3c1959d48c2af6cf81f9fc182d7/requirements.txt#L1) :>
3. [Kolory nadal smutne](https://github.com/Radioaktyv/JSProjekt/blob/4452d984a887c3c1959d48c2af6cf81f9fc182d7/main.py#L26) (3. rozdział).
4. [Zły styl nazwy](https://github.com/Radioaktyv/JSProjekt/blob/4452d984a887c3c1959d48c2af6cf81f9fc182d7/test.py#L6) (2. rozdział).
5. [`assertEqual(array, test_array)`](https://github.com/Radioaktyv/JSProjekt/blob/4452d984a887c3c1959d48c2af6cf81f9fc182d7/test.py#L17).
6. [Tu dodać pusty wiersz lub dwa](https://github.com/Radioaktyv/JSProjekt/blob/4452d984a887c3c1959d48c2af6cf81f9fc182d7/test.py#L42).
7. [`self.assertEqual(-main.next_turn(1), 1)`](https://github.com/Radioaktyv/JSProjekt/blob/4452d984a887c3c1959d48c2af6cf81f9fc182d7/test.py#L22).
8. Dodać jeszcze ze trzy testy i będzie OK.

**Comment by Radioaktyv** [comment]
Szanowny Panie Doktorze 
W związku z Pana zaleceniami dokonałem poprawek w kodzie tj. posortowałem importy alfabetycznie, zmieniłem kolory na te z palety Solarized, poprawiłem styl nazwy klasy, dodałem puste wiersze, uprościłem funkcje test_next_turn, oraz dodałem trzy nowe testy.
Gdy zmieniłem jednak test zgodnie z zaleceniami z podpunktu 5. otrzymałem taki błąd : "The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()".
Z wyrazami szacunku
Łukasz Murdzia

**Comment by MarcinCiura** [comment]
Użyć `array.tolist()` zamiast `array`.

**Comment by Radioaktyv** [comment]
Dziękuje za szybką odpowiedź. Użycie array.tolist() pomogło.

**Comment by MarcinCiura** [comment]
Nie rozbijać obliczeń na mini-kroki, do tego zmieniające typ i zawartość zmiennych. [Tu](https://github.com/Radioaktyv/JSProjekt/blob/a0ae6c1e0935c8ad9a0a1f370e8e542a80660206/test.py#L18) wystarczy `self.assertEqual(array.tolist(), test_array)`.

**Comment by Radioaktyv** [comment]
Poprawka została naniesiona.

**Comment by MarcinCiura** [comment]
Poproszę jeszcze o jakiś negatywny test dla metody `check_valid_location()`, czyli taki, gdzie niektóre kolumny są zapchane. `test_check_valid_location()` jakoś przemianować, np. dopisać `_empty_board` czy coś. Ten nowy test też nazwać tak, żeby z nazwy wynikało, co testuje, bo nazwy testów się wyświetlają w razie niepowodzenia. Dla spójności z istniejącym testem proponuję nieco zmienić sposób testowania:
```python
result = [main.check_valid_location(board, i) for i in range(main.COLUMN_COUNT)]  # Było błędnie ROW_COUNT.
self.assertEqual(result, [True, True, True, True, True, True, True])
```

**Comment by Radioaktyv** [comment]
Dodałem test który zawsze pokazuje fail, tak jak Pan prosił

**Comment by MarcinCiura** [comment]
Nie prosiłem o test, który nie przechodzi. Prosiłem o test `check_valid_location()` dla niektórych kolumn zapchanych w odróżnieniu od testu tejże metody dla pustej planszy,

**Comment by Radioaktyv** [comment]
![image](https://user-images.githubusercontent.com/65417001/85703591-cbb7bd00-b6df-11ea-924b-04aa2ee0626a.png)
Czy ma Pan na myśli coś takiego?

**Comment by MarcinCiura** [comment]
Nie. Mam na myśli wypełnienie niektórych kolumn `test_array` w całości pionkami, po czym sprawdzenie, że `result` jest równy np. `[True, False, True, True, False, True, True]`.

**Comment by Radioaktyv** [comment]
Poprawka została naniesiona.

**Comment by MarcinCiura** [comment]
Dlaczego `ROW_COUNT = 7`? Takie *Connect 4*, jakie ja znam, ma planszę 7 kolumn na 6 wierszy. Dlaczego przy pustym najwyższym wierszu dostajemy `check_valid_location() == False`?

**Comment by Radioaktyv** [comment]
Ostatnie wierz zostawiłem z myślą aby był na wybór kolumny, używam go również do rysowania.

**Comment by Radioaktyv** [comment]
a nie sprawdza ponieważ zrobiłem ROW_COUNT - 2 w funkcji check_valid_location
![image](https://user-images.githubusercontent.com/65417001/85718536-e6ddf900-b6ee-11ea-807c-69e782bb6722.png)

**Comment by MarcinCiura** [comment]
**Dużo** lepiej byłoby mieć `ROW_COUNT = 6`, a dodawać do niego 1 w miejscach, gdzie to potrzebne. Ale niech stracę, LGTM.
